config/routes.rb
Rails.application.routes.draw do

  root "root#top"
  get "/contact" => "root#contact"

  get 'tests/test'
  get 'tests/mypage'
  get 'tests/favoriteCoach'
  get 'tests/loginPage'
  get 'tests/questionsPage'
  get 'tests/reservationManagementPage'
  get 'tests/contactUsPage'
  get 'tests/topDemoPage'
  get 'tests/chatroom'


  get "users/:user_id/history" => "users#coaching_history", as: :history_user
  get "users/:user_id/reserve_coaching" => "users#reserve_coaching", as: :reserve_user
  get "users/:user_id/settings" => "users#settings", as: :settings_user

  post "users" => "users#create", as: :users
  get "users/new" => "users#new", as: :new_user
  get "users/:user_id/edit" => "users#edit", as: :edit_user
  get "users/:user_id" => "users#show", as: :user_show
  patch "users/:user_id" => "users#update", as: :user_update
  delete "users/:user_id" => "users#destroy", as: :user_destory
  get "detail/users/:user_id" => "users#detail", as: :user_detail
  patch "detail/users/:user_id" => "users#detail_update", as: :user_detail_update
  get "favorite_coach/:user_id" => "users#favorite_coach", as: :favorite_coach

  post "coaches" => "coaches#create", as: :coaches
  get "coaches/new" => "coaches#new", as: :new_coach
  get "coaches/:coach_id/edit" => "coaches#edit", as: :edit_coach
  get "coaches/:coach_id" => "coaches#show", as: :coach_show
  patch "coaches/:coach_id" => "coaches#update", as: :coach_update
  delete "coaches/:coach_id" => "coaches#destroy", as: :coach_destroy
  get "detail/coaches/:coach_id" => "coaches#detail", as: :coach_detail
  patch "detail/coaches/:coach_id" => "coaches#detail_update", as: :coach_detail_update
  get "message_show/coaches/:coach_id" => "coaches#message_show", as: :coach_message_show
  resources :coaches do
    post 'favorites' => 'favorites#create'
    delete 'c_favorites' => 'favorites#destroy'
  end

  get "coaches/:coach_id/review" => "coaches#review", as: :review_coach
  get "coaches/:coach_id/reservation" => "coaches#reservation", as: :reservation_coach
  get "coaches/:coach_id/top" => "coaches#top", as: :top_coach



  get "account_activations/:user_id/user_edit" => "account_activations#edit", as: :user_edit_account_activation
  get "account_activations/:coach_id/coach_edit" => "account_activations#coach_edit", as: :coach_edit_account_activation

  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :events

  get "messages/user_id" => "messages#user_index", as: :user_msg_index
  get "messages/coach_id" => "messages#coach_index", as: :coach_msg_index
  resources :messages, :only => [:create]

  resources :rooms, :only => [:create, :show]

  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"

  get "coach_login" => "coach_sessions#new"
  post "coach_login" => "coach_sessions#create"
  delete "coach_logout" => "coach_sessions#destroy"

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save :downcase_email
  before_create :create_activation_digest
  validates :email, presence: true, length: { maximum: 255 }, uniqueness: { case_sensitive: false }, on: :update_password
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, on: :update_password
  has_many :coaches, through: :favorites
  has_many :favorites
  has_many :messages
  has_many :rooms

  def self.from_omniauth(auth)
    user = User.where('email = ?', auth.info.email).first
    if user.blank?
      user = User.new
    end
    user.uid   = auth.uid
    user.provider = auth.provider
    user.name  = auth.info.name
    user.email = auth.info.email
    user.user_image  = URI.parse(auth.info.image)
    user.password = User.new_token
    user.password_confirmation = user.password
    user
  end

  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def activate
    update_attribute(:activated, true)
    update_attribute(:activated_at, Time.zone.now)
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest, User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  def receive_notification
    MessageMailer.receive_notification(self).deliver_now
  end

  def send_message(other_user, room_id, content)
    from_messages.create!(to_id: other_user.id, room_id: room_id, content: content)
  end

  private

    def downcase_email
      self.email = email.downcase
    end

    def create_activation_digest
        self.activation_token  = User.new_token
        self.activation_digest = User.digest(activation_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def settings
    @user = User.find(params[:user_id])
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:user_id])
  end

  def detail
    @user = User.find(params[:user_id])
  end

  def create
    @user = User.new(user_params)
      if @user.save
        @user.send_activation_email
        flash[:success] = "登録メールアドレスに本登録のURLを送信しました。"
        redirect_to root_url
      end
  end

  def detail_update
    @user = User.find(params[:user_id])
    @user.update_attributes(user_params)
    if @user.save
      flash[:success] = "登録が完了しました。"
      redirect_to user_show_url(@user)
    else
      render "detail"
    end
  end

  def password_update
    @user = User.find(params[:user_id])
    @user.update_attributes(user_params)
    if @user.save
      flash[:success] = "登録が完了しました。"
      redirect_to @user
    else
      render "detail"
    end
  end

  def favorite_coach
    @favorite_coaches = Favorite.where(user_id: params[:user_id])
  end

  private

    def user_params
      params.require(:user).permit(
        :name, :kana, :email, :birthday, :university, :department, :graduate_year, :greeting,
        :password, :password_confirmation, :remember_digest, :activation_digest, :activated, :activated_at,
        :user_image, :provider, :uid, :reset_digest, :reset_sent_at
      )
    end

    def correct_user
      @user = User.find_by(id: params[:user_id])
      redirect_to root_url unless current_user?(@user)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/coaching_history.html.erb
<main id="coaching_history">
  <div class="text-center">
    <h2>コーチング履歴</h2>
    <p>🔍キーワード検索</p>
    <div class="hitory-detail bg-lightgray">
      <h4 class="ml-4 pt-4">2019/10/24(Sun)</h4>
      <div class="content">
        <div class="sidebar">
          <img src="/default.jpg" alt="" class="user-icon">
          <p>重神 咲也 (22じゃ)</p>

          <p class="mb-0" style="">株式会社Cultiate</p>
          <span class="text-orange">📩メッセージを見る</span>

          <p>面談回数： 48回</p>

          <p>#神戸大学</p>
          <p>#エンジニア</p>

          <p>料金：　20,000円</p>
          
          <a href="" class="btn btn-primary">詳細</a>
        </div>
        <div class="mainbar">
          <div class="">
            <h5 class="subtitle mt-0">コーチング内容（必須）</h5>
            <select class="w-100">
              <option value="" selected>選択してください</option>
              <option value="1">Option 1</option>
              <option value="2">Option 2</option>
              <option value="3">Option 3</option>
            </select>
          </div>
          <h5 class="subtitle">内容詳細</h5>
          <textarea name="profile" id="" class="w-100" cols="30" rows="5">私の強みは「身体が丈夫」な点です。これまで大きな病気をしたことがありません。バランスの取れた食事や手洗いうがいなどを心掛けて、万全の体調を維持するようにしています。運動もしているので、健康や体力には人一倍自信があります。</textarea>

          <h5 class="subtitle">その他希望</h5>
          <textarea name="profile" id="" class="w-100" cols="30" rows="5">私の強みは「身体が丈夫」な点です。これまで大きな病気をしたことがありません。バランスの取れた食事や手洗いうがいなどを心掛けて、万全の体調を維持するようにしています。運動もしているので、健康や体力には人一倍自信があります。</textarea>
        </div>
      </div>
    </div>
    <div class="hitory-detail bg-lightgray">
      <h4 class="ml-4 pt-4">2019/10/24(Sun)</h4>
      <div class="content">
        <div class="sidebar">
          <img src="/default.jpg" alt="" class="user-icon">
          <p>重神 咲也 (22じゃ)</p>

          <p class="mb-0" style="">株式会社Cultiate</p>
          <span class="text-orange">📩メッセージを見る</span>

          <p>面談回数： 48回</p>

          <p>#神戸大学</p>
          <p>#エンジニア</p>

          <p>料金：　20,000円</p>
          
          <a href="" class="btn btn-primary">詳細</a>
        </div>
        <div class="mainbar">
          <div class="">
            <h5 class="subtitle mt-0">コーチング内容（必須）</h5>
            <select class="w-100">
              <option value="" selected>選択してください</option>
              <option value="1">Option 1</option>
              <option value="2">Option 2</option>
              <option value="3">Option 3</option>
            </select>
          </div>
          <h5 class="subtitle">内容詳細</h5>
          <textarea name="profile" id="" class="w-100" cols="30" rows="5">私の強みは「身体が丈夫」な点です。これまで大きな病気をしたことがありません。バランスの取れた食事や手洗いうがいなどを心掛けて、万全の体調を維持するようにしています。運動もしているので、健康や体力には人一倍自信があります。</textarea>

          <h5 class="subtitle">その他希望</h5>
          <textarea name="profile" id="" class="w-100" cols="30" rows="5">私の強みは「身体が丈夫」な点です。これまで大きな病気をしたことがありません。バランスの取れた食事や手洗いうがいなどを心掛けて、万全の体調を維持するようにしています。運動もしているので、健康や体力には人一倍自信があります。</textarea>
        </div>
      </div>
    </div>
    <div class="hitory-detail bg-lightgray">
      <h4 class="ml-4 pt-4">2019/10/24(Sun)</h4>
      <div class="content">
        <div class="sidebar">
          <div class="coach-profile">
            <img src="/default.jpg" alt="" class="user-icon">
            <p>重神 咲也 (22じゃ)</p>

            <p class="mb-0" style="">株式会社Cultiate</p>
            <span class="text-orange">📩メッセージを見る</span>

            <p>面談回数： 48回</p>

            <p>#神戸大学</p>
            <p>#エンジニア</p>

            <p>料金：　20,000円</p>
            
            <a href="" class="btn btn-primary">詳細</a>
          </div>
        </div>
        <div class="mainbar">
          <div class="">
            <h5 class="subtitle mt-0">コーチング内容（必須）</h5>
            <select class="w-100">
              <option value="" selected>選択してください</option>
              <option value="1">Option 1</option>
              <option value="2">Option 2</option>
              <option value="3">Option 3</option>
            </select>
          </div>
          <h5 class="subtitle">内容詳細</h5>
          <textarea name="profile" id="" class="w-100" cols="30" rows="5">私の強みは「身体が丈夫」な点です。これまで大きな病気をしたことがありません。バランスの取れた食事や手洗いうがいなどを心掛けて、万全の体調を維持するようにしています。運動もしているので、健康や体力には人一倍自信があります。</textarea>

          <h5 class="subtitle">その他希望</h5>
          <textarea name="profile" id="" class="w-100" cols="30" rows="5">私の強みは「身体が丈夫」な点です。これまで大きな病気をしたことがありません。バランスの取れた食事や手洗いうがいなどを心掛けて、万全の体調を維持するようにしています。運動もしているので、健康や体力には人一倍自信があります。</textarea>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/users/detail.html.erb
</br>
</br>
</br>
</br>
</br>
<main>
  <div>
  <%= form_for(@user, url: user_detail_update_path) do |f| %>

    <%= f.label :name, "名前" %>
    <%= f.text_field :name, placeholder:"山田太郎" %>

    <%= f.label :kana, "カナ" %>
    <%= f.text_field :kana, placeholder:"ヤマダタロウ" %>

    <%= f.label :birthday, "生年月日" %>
    <%= f.text_field :birthday, placeholder:"1995年1月1日" %>

    <%= f.label :university, "大学名" %>
    <%= f.text_field :university, placeholder:"PAISEN大学" %>

    <%= f.label :department, "学部" %>
    <%= f.text_field :department, placeholder:"PAISEN学部" %>

    <%= f.label :graduate_year, "生年月日" %>
    <%= f.text_field :graduate_year, placeholder:"2020年 3月卒" %>

    <%= f.submit "登録" %>
  <% end %>
  </div>
</main>

app/views/users/favorite_coach.html.erb
<br>
<br>
<br>
<br>

<p class="text-center">・お気に入りコーチ一覧</p>
<div class="container" style="max-width: 100%; margin:0px 40px 0px">
  <div class="row justify-content-center">
    <div class="col-8">
      <input class="form-control" type="text" placeholder="コーチ名を入力してください">
    </div>
    <div class="col-2">
      <button type="button" class="btn btn-secondary">検索</button>
    </div>
  </div>
</div>

<br>
<div class="container" >
  <table class="table" style="max-width: 100%; margin-top:40px;">
    <thead>
      <tr>
        <th scope="col">アイコン</th>
        <th scope="col">名前</th>
        <th scope="col">会社名</th>
        <th scope="col">コーチング回数</th>
        <th scope="col">業種</th>
        <th scope="col">職種</th>
        <th scope="col">予約</th>
      </tr>
    </thead>
    <tbody>
      <% @favorite_coaches.each do |fav_coach| %>
        <% @coach = Coach.find_by(id: fav_coach.coach_id) %>
          <%= @coach.name %>
      <% end %>
      <tr>
        <td><img src="/assets/gitchan.jpg" width="100px" height="50px"　class="rounded-circle"></td>
        <td>名無しさん</td>
        <td>某会社</td>
        <td>3回</td>
        <td>IT</td>
        <td>エンジニア</td>
        <td><button type="button" class="btn btn-secondary">予約</button></td>
      </tr>
      <tr>
        <td><img src="/assets/gitchan.jpg" width="100px" height="50px"　class="rounded-circle"></td>
        <td>名無しさん</td>
        <td>某会社</td>
        <td>3回</td>
        <td>IT</td>
        <td>エンジニア</td>
        <td><button type="button" class="btn btn-secondary">予約</button></td>
      </tr>
      <tr>
        <td><img src="/assets/gitchan.jpg" width="80px" height="50px"　class="rounded-circle"></td>
        <td>名無しさん</td>
        <td>某会社</td>
        <td>3回</td>
        <td>IT</td>
        <td>エンジニア</td>
        <td><button type="button" class="btn btn-secondary">予約</button></td>
      </tr>
    </tbody>
  </table>
</div>

app/views/users/new.html.erb
</br>
</br>
</br>
</br>
</br>
<main>
  <div>
  <%= form_for(@user, url: users_path) do |f| %>
    <%= f.label :email, "メールアドレス" %>
    <%= f.email_field :email, placeholder:"info@example.com" %>
    <%= f.label :password, "パスワード" %>
    <%= f.password_field :password, placeholder:"英数字8文字以上" %>
    <%= f.label :password_confirmation, "パスワード(確認)" %>
    <%= f.password_field :password_confirmation, placeholder:"英数字8文字以上" %>

    <%= f.submit "登録" %>
  <% end %>
  </div>
</main>

app/views/users/reserve_coaching.html.erb
<main id="reserve_coaching">
  <div class="text-center">
    <h2>コーチング予約</h2>
    <p>選択されたコーチングの内容は以下の通りです。問題がなければ予約を確定するボタンを押して先に進めてください。</p>
    <div class="hitory-detail bg-lightgray">
      <h4 class="pt-4">2019/10/24(Sun)</h4>
      <div class="content">
        <div class="sidebar">
          <img src="/default.jpg" alt="" class="user-icon">
          <p>重神 咲也 (22じゃ)</p>

          <p class="mb-0" style="">株式会社Cultiate</p>
          <span class="text-orange">📩メッセージを見る</span>

          <p>面談回数： 48回</p>

          <p>#神戸大学</p>
          <p>#エンジニア</p>

          <p>料金：　20,000円</p>
          
          <a href="" class="btn btn-primary">詳細</a>
        </div>
        <div class="mainbar">
          <div class="">
            <h5 class="subtitle mt-0">コーチング内容（必須）</h5>
            <select class="w-100">
              <option value="" selected>選択してください</option>
              <option value="1">Option 1</option>
              <option value="2">Option 2</option>
              <option value="3">Option 3</option>
            </select>
          </div>
          <h5 class="subtitle">内容詳細</h5>
          <textarea name="profile" id="" class="w-100" cols="30" rows="5">私の強みは「身体が丈夫」な点です。これまで大きな病気をしたことがありません。バランスの取れた食事や手洗いうがいなどを心掛けて、万全の体調を維持するようにしています。運動もしているので、健康や体力には人一倍自信があります。</textarea>

          <h5 class="subtitle">その他希望</h5>
          <textarea name="profile" id="" class="w-100" cols="30" rows="5">私の強みは「身体が丈夫」な点です。これまで大きな病気をしたことがありません。バランスの取れた食事や手洗いうがいなどを心掛けて、万全の体調を維持するようにしています。運動もしているので、健康や体力には人一倍自信があります。</textarea>
        </div>
        
      </div>
    </div>
  </div>
</main>

app/views/users/settings.html.erb
<main id="settings">
  <h2 class="text-center">各種設定</h2>
  <div class="content">
    <div class="sidebar">
      <ul>
        <li>基本情報設定</li>
        <li>メール通知設定</li>
        <li>決済設定</li>
      </ul>
    </div>
    <div class="mainbar">
      <form>
        <div class="form-group">
          <label for="exampleInputEmail1">名前</label>
          <input type="email" class="form-control rounded-pill" id="exampleInputEmail1" placeholder="pai sen">
        </div>
        <div class="form-group">
          <label for="exampleInputPassword1">ふりがな</label>
          <input type="password" class="form-control rounded-pill" id="exampleInputPassword1" placeholder="ぱいせん">
        </div>
        <label for="exampleInputBirth" class="">生年月日</label>
        <div class="form-row">
          <div class="col">
            <input type="text" class="form-control rounded-pill" placeholder="2019">年
          </div>
          <div class="col">
            <input type="text" class="form-control rounded-pill" placeholder="2">月
          </div>
          <div class="col">
            <input type="text" class="form-control rounded-pill" placeholder="19">日
          </div>
        </div>
        <label for="exampleInputBirth" class="">性別</label>
        <div class="form-check form-check-inline">
          <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1" value="option1">
          <label class="form-check-label">男性</label>
        </div>
        <div class="form-check form-check-inline">
          <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio2" value="option2">
          <label class="form-check-label">女性</label>
        </div>
        <div class="d-block">
          <button type="submit" class="btn btn-primary mt-4">保存する</button>
        </div>
      </form>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<main id="mypage">
  <div class="overflow-hidden text-center">
    <h2 class="title">プロフィール</h2>
    <div class="sidebar">
      <div class="user-profile">
        <img src="/default.jpg" alt="" class="user-icon">
        <p>松本　ことみ (20)</p>

        <p>京都精華大学 染織専攻<br>
        2022年度卒業</p>

        <div class="detail-profile">
          <h5 class="subtitle">学歴</h5>
          <p>京都精華大学<br>
          芸術学部  染織専攻<br>
          大阪府刀根山高校</p>

          <h5 class="subtitle">部活動・サークル</h5>
          <p>バレーボールサークル</p>

          <h5 class="subtitle">インターン履歴</h5>
          <p>株式会社Cultiate<br>
          pai_sen株式会社<br>
          株式会社LeaGLO</p>
        </div>
      </div>
    </div>
    <div class="mainbar">
      <div class="content">
        <h5 class="subtitle" style="margin-top:0;">自己紹介</h5>
        <textarea name="profile" id="" class="profile-edit" cols="30" rows="5">私の強みは「身体が丈夫」な点です。これまで大きな病気をしたことがありません。バランスの取れた食事や手洗いうがいなどを心掛けて、万全の体調を維持するようにしています。運動もしているので、健康や体力には人一倍自信があります。</textarea>

        <h5 class="subtitle">今後やってみたいこと</h5>
        <textarea name="profile" id="" class="profile-edit" cols="30" rows="5">私の強みは「身体が丈夫」な点です。これまで大きな病気をしたことがありません。バランスの取れた食事や手洗いうがいなどを心掛けて、万全の体調を維持するようにしています。運動もしているので、健康や体力には人一倍自信があります。</textarea>

        <h5 class="subtitle">興味のある業界・分野</h5>
        <textarea name="profile" id="" class="profile-edit" cols="30" rows="5">私の強みは「身体が丈夫」な点です。これまで大きな病気をしたことがありません。バランスの取れた食事や手洗いうがいなどを心掛けて、万全の体調を維持するようにしています。運動もしているので、健康や体力には人一倍自信があります。</textarea>
      </div>
    </div>
  </div>
</main>

<%# 
<br><br><br>
<div class="card" style="width: auto; margin:40px;">
  <img class="card-img-top" src="/assets/gitchan.jpg" alt="Card image cap">
  <div class="card-body" style="width: auto; margin-top:40px;">
    <h5 class="card-title">名前 : 苗字　名</h5>
    <p class="card-text">大学 ： 甲南大学　知能情報学部　知能情報学科</p>
    <p class="card-text">志望業界 ： IT,金融,人材</p>
  </div>
</div>


<div class="progress mt-3" style="width: auto; margin:40px;">
  <div class="progress-bar" role="progressbar" style="width: 25%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">25%</div>
</div>

<button type="button" class="btn btn-secondary float-right" style="width: auto; margin:0px 40px 0px;">編集する</button>
<form class="" action="index.html" method="post">
  <div class="form-group"style="width: auto; margin:0px 40px 0px;">
   <label for="exampleFormControlTextarea1">自己紹介</label>
   <textarea class="form-control" id="exampleFormControlTextarea1" rows="5"></textarea>
  </div>
</form>
<br>

<button type="button" class="btn btn-secondary float-right" style="width: auto; margin:0px 40px 0px;">編集する</button>
<form class="" action="index.html" method="post">
  <div class="form-group"style="width: auto; margin:0px 40px 0px;">
   <label for="exampleFormControlTextarea1">今後やってみたいこと</label>
   <textarea class="form-control" id="exampleFormControlTextarea1" rows="5"></textarea>
  </div>
</form>
<br>

<button type="button" class="btn btn-secondary float-right" style="width: auto; margin:0px 40px 0px;">編集する</button>
<form class="" action="index.html" method="post">
  <div class="form-group"style="width: auto; margin:0px 40px 0px;">
   <label for="exampleFormControlTextarea1">学歴</label>
   <textarea class="form-control" id="exampleFormControlTextarea1" rows="5"></textarea>
  </div>
</form>
<br>

<button type="button" class="btn btn-secondary float-right" style="width: auto; margin:0px 40px 0px;">編集する</button>
<form class="" action="index.html" method="post">
  <div class="form-group"style="width: auto; margin:0px 40px 0px;">
   <label for="exampleFormControlTextarea1">ゼミ活動</label>
   <textarea class="form-control" id="exampleFormControlTextarea1" rows="2"></textarea>
  </div>
</form>
<br>

<button type="button" class="btn btn-secondary float-right" style="width: auto; margin:0px 40px 0px;">編集する</button>
<form class="" action="index.html" method="post">
  <div class="form-group"style="width: auto; margin:0px 40px 0px;">
   <label for="exampleFormControlTextarea1">インターン・課外活動</label>
   <textarea class="form-control" id="exampleFormControlTextarea1" rows="2" maxlength='8'></textarea>
  </div>
</form>
<!-- maxlength='8' で文字数制限かけられる-->




 <br><br> %>