config/routes.rb
Rails.application.routes.draw do

  root "root#top"
  get "/contact" => "root#contact"

  get 'tests/test'
  get 'tests/mypage'
  get 'tests/favoriteCoach'
  get 'tests/loginPage'
  get 'tests/questionsPage'
  get 'tests/reservationManagementPage'
  get 'tests/contactUsPage'
  get 'tests/topDemoPage'
  get 'tests/chatroom'


  get "users/:user_id/history" => "users#coaching_history", as: :history_user
  get "users/:user_id/reserve_coaching" => "users#reserve_coaching", as: :reserve_user
  get "users/:user_id/settings" => "users#settings", as: :settings_user

  post "users" => "users#create", as: :users
  get "users/new" => "users#new", as: :new_user
  get "users/:user_id/edit" => "users#edit", as: :edit_user
  get "users/:user_id" => "users#show", as: :user_show
  patch "users/:user_id" => "users#update", as: :user_update
  delete "users/:user_id" => "users#destroy", as: :user_destory
  get "detail/users/:user_id" => "users#detail", as: :user_detail
  patch "detail/users/:user_id" => "users#detail_update", as: :user_detail_update
  get "favorite_coach/:user_id" => "users#favorite_coach", as: :favorite_coach

  post "coaches" => "coaches#create", as: :coaches
  get "coaches/new" => "coaches#new", as: :new_coach
  get "coaches/:coach_id/edit" => "coaches#edit", as: :edit_coach
  get "coaches/:coach_id" => "coaches#show", as: :coach_show
  patch "coaches/:coach_id" => "coaches#update", as: :coach_update
  delete "coaches/:coach_id" => "coaches#destroy", as: :coach_destroy
  get "detail/coaches/:coach_id" => "coaches#detail", as: :coach_detail
  patch "detail/coaches/:coach_id" => "coaches#detail_update", as: :coach_detail_update
  get "message_show/coaches/:coach_id" => "coaches#message_show", as: :coach_message_show
  resources :coaches do
    post 'favorites' => 'favorites#create'
    delete 'c_favorites' => 'favorites#destroy'
  end

  get "coaches/:coach_id/review" => "coaches#review", as: :review_coach
  get "coaches/:coach_id/reservation" => "coaches#reservation", as: :reservation_coach
  get "coaches/:coach_id/top" => "coaches#top", as: :top_coach



  get "account_activations/:user_id/user_edit" => "account_activations#edit", as: :user_edit_account_activation
  get "account_activations/:coach_id/coach_edit" => "account_activations#coach_edit", as: :coach_edit_account_activation

  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :events

  get "messages/user_id" => "messages#user_index", as: :user_msg_index
  get "messages/coach_id" => "messages#coach_index", as: :coach_msg_index
  resources :messages, :only => [:create]

  resources :rooms, :only => [:create, :show]

  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"

  get "coach_login" => "coach_sessions#new"
  post "coach_login" => "coach_sessions#create"
  delete "coach_logout" => "coach_sessions#destroy"

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/coach.rb
class Coach < ApplicationRecord
  has_many :users, through: :favorites
  has_many :favorites
  has_many :messages
  has_many :rooms
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save :downcase_email
  before_create :create_activation_digest
  validates :email, presence: true, length: { maximum: 255 }, uniqueness: { case_sensitive: false }, on: :update_password
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, on: :update_password

  def self.from_omniauth(auth)
    coach = Coach.where('email = ?', auth.info.email).first
    if coach.blank?
      coach = Coach.new
    end
    coach.uid   = auth.uid
    coach.provider = auth.provider
    coach.name  = auth.info.name
    coach.email = auth.info.email
    self.coach_image  = URI.parse(auth.info.image)
    coach.password = Coach.new_token
    coach.password_confirmation = coach.password
    coach
  end

  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def remember_coach
    self.remember_token = Coach.new_token
    update_attribute(:remember_digest, Coach.digest(remember_token))
  end

  def forget_coach
    update_attribute(:remember_digest, nil)
  end

  def authenticated_coach?(remember_token, token)
    digest = self.send('remember_digest')
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(remember_token)
  end

  def activate
    update_attribute(:activated, true)
    update_attribute(:activated_at, Time.zone.now)
  end

  def send_activation_email
    CoachMailer.account_activation(self).deliver_now
  end

  def create_reset_digest
    self.reset_token = Coach.new_token
    update_attribute(:reset_digest, Coach.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  def send_password_reset_email
    CoachMailer.password_reset(self).deliver_now
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  def receive_notification
    MessageMailer.receive_notification(self).deliver_now
  end

  private

    def downcase_email
      self.email = email.downcase
    end

    def create_activation_digest
        self.activation_token  = Coach.new_token
        self.activation_digest = Coach.digest(activation_token)
    end
end

app/controllers/coaches_controller.rb
class CoachesController < ApplicationController


  def top
    @coach = Coach.find(params[:coach_id])
  end

  def reservation
    @coach = Coach.find(params[:coach_id])
  end

  def review
    @coach = Coach.find(params[:coach_id])
  end

  def new
    @coach = Coach.new
  end

  def show
    @coach = Coach.find(params[:coach_id])
  end

  def detail
    @coach = Coach.find(params[:coach_id])
  end

  def create
    @coach = Coach.new(coach_params)
      if @coach.save
        @coach.send_activation_email
        flash[:success] = "登録メールアドレスに本登録のURLを送信しました。"
        redirect_to root_url
      end
  end

  def detail_update
    @coach = Coach.find(params[:coach_id])
    @coach.update_attributes(coach_params)
    if @coach.save
      flash[:success] = "登録が完了しました。"
      redirect_to @coach
    else
      render "detail"
    end
  end

  def password_update
    @coach = Coach.find(params[:coach_id])
    @coach.update_attributes(coach_params)
    if @coach.save
      flash[:success] = "登録が完了しました。"
      redirect_to @coach
    else
      render "detail"
    end
  end

  private

    def coach_params
      params.require(:coach).permit(
        :name, :kana, :email, :birthday, :status, :company, :business, :occupation, :greeting, :coaching_fee,
        :password, :password_confirmation, :remember_digest, :activation_digest, :activated, :activated_at,
        :coach_image, :provider, :uid, :reset_digest, :reset_sent_at
      )
    end

    def correct_coach
      @coach = Coach.find_by(id: params[:coach_id])
      redirect_to root_url unless current_coach?(@coach)
    end
end

app/helpers/coaches_helper.rb
module CoachesHelper
end

app/views/coaches/detail.html.erb
</br>
</br>
</br>
</br>
</br>
<main>
  <div>
  <%= form_for(@coach, url: coach_detail_update_path) do |f| %>

    <%= f.label :name, "名前" %>
    <%= f.text_field :name, placeholder:"山田太郎" %>

    <%= f.label :kana, "カナ" %>
    <%= f.text_field :kana, placeholder:"ヤマダタロウ" %>

    <%= f.label :birthday, "生年月日" %>
    <%= f.text_field :birthday, placeholder:"1995年1月1日" %>

    <%= f.label :company, "会社名" %>
    <%= f.text_field :company, placeholder:"株式会社PAISEN" %>

    <%= f.label :business, "職業" %>
    <%= f.text_field :business, placeholder:"会社員" %>

    <%= f.label :occupation, "職種" %>
    <%= f.text_field :occupation, placeholder:"営業" %>

    <%= f.label :occupation, "職種" %>
    <%= f.text_field :occupation, placeholder:"営業" %>

    <%= f.label :greeting, "自己紹介文" %>
    <%= f.text_field :greeting, placeholder:"自己紹介文" %>

    <%= f.label :coaching_fee, "コーチ料金設定" %>
    <%= f.text_field :coaching_fee, placeholder:"2500円/h" %>

    <%= f.submit "登録" %>
  <% end %>
  </div>
</main>

app/views/coaches/new.html.erb
</br>
</br>
</br>
</br>
</br>
<main>
  <div>
  <%= form_for(@coach, url: coaches_path) do |f| %>
    <%= f.check_box :status %>
    <%= f.label :status, "内定者の方はこちらをチェックしてください。" %>
    <%= f.label :email, "メールアドレス" %>
    <%= f.email_field :email, placeholder:"info@example.com" %>
    <%= f.label :password, "パスワード" %>
    <%= f.password_field :password, placeholder:"英数字8文字以上" %>
    <%= f.label :password_confirmation, "パスワード(確認)" %>
    <%= f.password_field :password_confirmation, placeholder:"英数字8文字以上" %>

    <%= f.submit "登録" %>
  <% end %>
  </div>
</main>

app/views/coaches/reservation.html.erb
<main id="reservation_coach">
  <div class="content">
    <h2>予約管理</h2>
    <form class="form-inline mt-2 mt-md-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
    <div class="reservations accordion text-left" id="accordion2" role="tablist">
      <div class="card">
        <div class="card-header" role="tab" id="heading1">
          <h5 class="mb-0">
            <a data-toggle="collapse" class="text-body stretched-link text-decoration-none" href="#collapse1" aria-expanded="true" aria-controls="collapse1">
            <div class="reservation overflow-hidden">
              <img src="/default.jpg" alt="" class="user-icon reserver-icon float-left">
              <div class="reserve-info float-left">
                <p class="text-left mb-0">2/19 15:00~16:00</p>
                <h4 class="reserver-profile">松本 ことみ さん</h4>
              </div>
            </div>
            </a>
          </h5>
        </div>
        <div id="collapse1" class="collapse show" role="tabpanel" aria-labelledby="heading1" data-parent="#accordion2">
          <div class="card-body">
            <span class="" style="font-size:12px;">京都精華大学</span><br><a href="#" style="font-size:12px;"><i><img src="/icons/c-fav.png" alt=""></i>プロフィールを見る</a>
            <div class="tags my-5">
              <a href="#" class="tag">#テキスタイル専攻</a>
              <a href="#" class="tag">#2回生</a>
              <a href="#" class="tag">#デザイナー志望</a>
            </div>
            <div class="text-left overflow-hidden">
              <div class="col-sm-6 float-left">
                <div class="subject">
                  <h4>コーチング内容</h4>
                  <p class="ml-4">サンプルテキスト</p>
                </div>
                <div class="detail">
                  <h4>内容詳細</h4>
                  <p class="ml-4">この文章はダミーです。文字の大きさ、量、字間、行間等を確認するために入れています。この文章はダミーです。文字の大きさ、量、字間、行間等を確認するために入れています。この文章はダミーです。文字１００文字この文章はダミーです。文字の大きさ、量、字間、行間等を確認するために入れています。この文章はダミーです。文字の大きさ、量、字間、行間等を確認するために入れています。この文章はダミーです。文字２００文字</p>
                </div>
              </div>
              <div class="col-sm-6 float-left">
                <div class="profile">
                  <h4>自己紹介</h4>
                  <p class="ml-4">この文章はダミーです。文字の大きさ、量、字間、行間等を確認するために入れています。この文章はダミーです。文字の大きさ、量、字間、行間等を確認するために入れています。この文章はダミーです。文字１００文字</p>
                </div>
                <div class="others">
                  <h4>その他希望</h4>
                  <p class="ml-4">この文章はダミーです。文字の大きさ、量、字間、行間等を確認するために入れています。この文章はダミーです。文字の大きさ、量、字間、行間等を確認するために入れています。この文章はダミーです。文字１００文字</p>
                </div>
              </div>
            </div>
            <div class="buttons text-center mt-4">
              <a href="#" class="btn btn-danger mx-2">メッセージを送る</a>
              <a href="#" class="btn btn-primary mx-2">予約をキャンセルする</a>
            </div>
          </div>
        </div>
      </div>
      <div class="card">
        <div class="card-header" role="tab" id="heading2">
          <h5 class="mb-0">
            <a class="collapsed text-body stretched-link text-decoration-none" data-toggle="collapse" href="#collapse2" aria-expanded="false" aria-controls="collapse2">
            <div class="reservation overflow-hidden">
              <img src="/default.jpg" alt="" class="user-icon reserver-icon float-left">
              <div class="reserve-info float-left">
                <p class="text-left mb-0">2/19 17:00~18:00</p>
                <h4 class="reserver-profile">松本 ことみ さん</h4>
              </div>
            </div>
            </a>
          </h5>
        </div>
        <div id="collapse2" class="collapse" role="tabpanel" aria-labelledby="heading2" data-parent="#accordion2">
          <div class="card-body">
            <span class="" style="font-size:12px;">京都精華大学</span><br><a href="#" style="font-size:12px;"><i><img src="/icons/c-fav.png" alt=""></i>プロフィールを見る</a>
            <div class="tags my-5">
              <a href="#" class="tag">#テキスタイル専攻</a>
              <a href="#" class="tag">#2回生</a>
              <a href="#" class="tag">#デザイナー志望</a>
            </div>
            <div class="text-left overflow-hidden">
              <div class="col-sm-6 float-left">
                <div class="subject">
                  <h4>コーチング内容</h4>
                  <p class="ml-4">サンプルテキスト</p>
                </div>
                <div class="detail">
                  <h4>内容詳細</h4>
                  <p class="ml-4">この文章はダミーです。文字の大きさ、量、字間、行間等を確認するために入れています。この文章はダミーです。文字の大きさ、量、字間、行間等を確認するために入れています。この文章はダミーです。文字１００文字この文章はダミーです。文字の大きさ、量、字間、行間等を確認するために入れています。この文章はダミーです。文字の大きさ、量、字間、行間等を確認するために入れています。この文章はダミーです。文字２００文字</p>
                </div>
              </div>
              <div class="col-sm-6 float-left">
                <div class="profile">
                  <h4>自己紹介</h4>
                  <p class="ml-4">この文章はダミーです。文字の大きさ、量、字間、行間等を確認するために入れています。この文章はダミーです。文字の大きさ、量、字間、行間等を確認するために入れています。この文章はダミーです。文字１００文字</p>
                </div>
                <div class="others">
                  <h4>その他希望</h4>
                  <p class="ml-4">この文章はダミーです。文字の大きさ、量、字間、行間等を確認するために入れています。この文章はダミーです。文字の大きさ、量、字間、行間等を確認するために入れています。この文章はダミーです。文字１００文字</p>
                </div>
              </div>
            </div>
            <div class="buttons text-center mt-4">
              <a href="#" class="btn btn-danger mx-2">メッセージを送る</a>
              <a href="#" class="btn btn-primary mx-2">予約をキャンセルする</a>
            </div>
          </div>
        </div>
      </div>
      <div class="card">
        <div class="card-header" role="tab" id="heading3">
          <h5 class="mb-0">
            <a class="collapsed text-body stretched-link text-decoration-none" data-toggle="collapse" href="#collapse3" aria-expanded="false" aria-controls="collapse3">
            <div class="reservation overflow-hidden">
              <img src="/default.jpg" alt="" class="user-icon reserver-icon float-left">
              <div class="reserve-info float-left">
                <p class="text-left mb-0">2/19 18:00~19:00</p>
                <h4 class="reserver-profile">松本 ことみ さん</h4>
              </div>
            </div>
            </a>
          </h5>
        </div>
        <div id="collapse3" class="collapse" role="tabpanel" aria-labelledby="heading3" data-parent="#accordion2">
          <div class="card-body">
            <span class="" style="font-size:12px;">京都精華大学</span><br><a href="#" style="font-size:12px;"><i><img src="/icons/c-fav.png" alt=""></i>プロフィールを見る</a>
            <div class="tags my-5">
              <a href="#" class="tag">#テキスタイル専攻</a>
              <a href="#" class="tag">#2回生</a>
              <a href="#" class="tag">#デザイナー志望</a>
            </div>
            <div class="text-left overflow-hidden">
              <div class="col-sm-6 float-left">
                <div class="subject">
                  <h4>コーチング内容</h4>
                  <p class="ml-4">サンプルテキスト</p>
                </div>
                <div class="detail">
                  <h4>内容詳細</h4>
                  <p class="ml-4">この文章はダミーです。文字の大きさ、量、字間、行間等を確認するために入れています。この文章はダミーです。文字の大きさ、量、字間、行間等を確認するために入れています。この文章はダミーです。文字１００文字この文章はダミーです。文字の大きさ、量、字間、行間等を確認するために入れています。この文章はダミーです。文字の大きさ、量、字間、行間等を確認するために入れています。この文章はダミーです。文字２００文字</p>
                </div>
              </div>
              <div class="col-sm-6 float-left">
                <div class="profile">
                  <h4>自己紹介</h4>
                  <p class="ml-4">この文章はダミーです。文字の大きさ、量、字間、行間等を確認するために入れています。この文章はダミーです。文字の大きさ、量、字間、行間等を確認するために入れています。この文章はダミーです。文字１００文字</p>
                </div>
                <div class="others">
                  <h4>その他希望</h4>
                  <p class="ml-4">この文章はダミーです。文字の大きさ、量、字間、行間等を確認するために入れています。この文章はダミーです。文字の大きさ、量、字間、行間等を確認するために入れています。この文章はダミーです。文字１００文字</p>
                </div>
              </div>
            </div>
            <div class="buttons text-center mt-4">
              <a href="#" class="btn btn-danger mx-2">メッセージを送る</a>
              <a href="#" class="btn btn-primary mx-2">予約をキャンセルする</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/coaches/review.html.erb
<main id="review_coach">
  <div class="content text-center">
    <h4>レビュー</h4>
    <p class="mt-4">⭐️️️️️️️️⭐️️️️️️️️⭐️️️️️️️️⭐️️️️️️️️⭐️️️️️️️️<span class="ml-2">5.0</span></p>
    <div class="reviews">
      <ul class="review row">
        <li class="col-2">⭐️ ５</li>
        <li class="col-10">
          <div class="progress">
            <div class="progress-bar" role="progressbar" style="width: 95%" aria-valuenow="95" aria-valuemin="0" aria-valuemax="100"></div>
          </div>
        </li>
      </ul>
      <ul class="review row">
        <li class="col-2">⭐️ 4</li>
        <li class="col-10">
          <div class="progress">
            <div class="progress-bar" role="progressbar" style="width: 75%" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
          </div>
        </li>
      </ul>
      <ul class="review row">
        <li class="col-2">⭐️ 3</li>
        <li class="col-10">
          <div class="progress">
            <div class="progress-bar" role="progressbar" style="width: 50%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
          </div>
        </li>
      </ul>
      <ul class="review row">
        <li class="col-2">⭐️ 2</li>
        <li class="col-10">
          <div class="progress">
            <div class="progress-bar" role="progressbar" style="width: 15%" aria-valuenow="15" aria-valuemin="0" aria-valuemax="100"></div>
          </div>
        </li>
      </ul>
      <ul class="review row">
        <li class="col-2">⭐️ 1</li>
        <li class="col-10">
          <div class="progress">
            <div class="progress-bar" role="progressbar" style="width: 0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
          </div>
        </li>
      </ul>
    </div>
    <div class="dropdown text-right mr-4">
      <button class="btn btn-outline-info dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        並び替え　　　　　　　　　　
      </button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <a class="dropdown-item" href="#">Action</a>
        <a class="dropdown-item" href="#">Another action</a>
        <a class="dropdown-item" href="#">Something else here</a>
      </div>
    </div>
    <div class="detail-reviews">
      <div class="detail-review">
        <div class="overflow-hidden">
          <div class="reviewer-img float-left">
            <img src="/default.jpg" alt="" class="user-icon">
            <p>松本 ことみ (20)</p>
          </div>
          <div class="reviewer-text float-left">
            <div class="border p-4">
              <p class="mb-0" >この文章はダミーです。文字の大きさ、量、字間、行間等を確認するために入れています。この文章はダミーです。文字の大きさ、量、字間、行間等を確認するために入れています。この文章はダミーです。文字１００文字この文章はダミーです。文字の大きさ、量、字間、行間等を確認するために入れています。この文章はダミーです。文字の大きさ、量、字間、行間等を確認するために入れています。この文章はダミーです。文字２００文字</p>
              ️<p class="text-right mb-0"><span class="date mr-5">2019/10/29</span>⭐️️️️️️️️⭐️️️️️️️️⭐️️️️️️️️⭐️️️️️️️️☆</p>
            </div>
          </div>
        </div>
      </div>
      <div class="detail-review">
        <div class="overflow-hidden">
          <div class="reviewer-img float-left">
            <img src="/default.jpg" alt="" class="user-icon">
            <p>松本 ことみ (20)</p>
          </div>
          <div class="reviewer-text float-left">
            <div class="border p-4">
              <p class="mb-0" >この文章はダミーです。文字の大きさ、量、字間、行間等を確認するために入れています。この文章はダミーです。文字の大きさ、量、字間、行間等を確認するために入れています。この文章はダミーです。文字１００文字この文章はダミーです。文字の大きさ、量、字間、行間等を確認するために入れています。この文章はダミーです。文字の大きさ、量、字間、行間等を確認するために入れています。この文章はダミーです。文字２００文字</p>
              ️<p class="text-right mb-0"><span class="date mr-5">2019/10/29</span>⭐️️️️️️️️⭐️️️️️️️️⭐️️️️️️️️⭐️️️️️️️️☆</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/coaches/show.html.erb
<main id="mypage_coach">
  <div class="overflow-hidden text-center">
    <h2 class="title">プロフィール</h2>
    <div class="sidebar">
      <div class="user-profile">
        <div class="text-right mb-2 mr--8">
          <a href="#" class="border rounded p-1 pl-2 text-orange">編集する<img src="/icons/c-pencil.png" alt="" class="w-15"></a>
        </div>
        <img src="/default.jpg" alt="" class="user-icon">
        <p>立花 祐輔 (27)</p>

        <p>株式会社Cultiate<br>
        #エンジニア</p>

        <div class="detail-profile">
          <h5 class="subtitle">学歴</h5>
          <p>関西学院大学<br>
          商学部  商学科<br>
          2015年度卒業</p>

          <h5 class="subtitle">職歴</h5>
          <p>キーエンス株式会社 2015~2017</p>
          <p>株式会社Cultiate 取締役 2018~</p>
          <p>SHUKUFUKU株式会社 CTO 2018~</p>
        </div>
      </div>
    </div>
    <div class="mainbar">
      <div class="content">
        <h5 class="subtitle" style="margin-top:0;">自己紹介</h5>
        <textarea name="profile" id="" class="profile-edit" cols="30" rows="5">私の強みは「身体が丈夫」な点です。これまで大きな病気をしたことがありません。バランスの取れた食事や手洗いうがいなどを心掛けて、万全の体調を維持するようにしています。運動もしているので、健康や体力には人一倍自信があります。</textarea>

        <h5 class="subtitle">学生時代の活動</h5>
        <textarea name="profile" id="" class="profile-edit" cols="30" rows="5">私の強みは「身体が丈夫」な点です。これまで大きな病気をしたことがありません。バランスの取れた食事や手洗いうがいなどを心掛けて、万全の体調を維持するようにしています。運動もしているので、健康や体力には人一倍自信があります。</textarea>

        <h5 class="subtitle">話せる内容</h5>
        <textarea name="profile" id="" class="profile-edit" cols="30" rows="5">私の強みは「身体が丈夫」な点です。これまで大きな病気をしたことがありません。バランスの取れた食事や手洗いうがいなどを心掛けて、万全の体調を維持するようにしています。運動もしているので、健康や体力には人一倍自信があります。</textarea>
      </div>
    </div>
  </div>
</main>

<<<<<<< HEAD
</div>
=======
  <%# <%= form_for @message do |f| %> %>
    <%# <%= f.text_field :content, :placeholder => "メッセージを入力して下さい" %> %>
    <%# <%= f.hidden_field :room_id, :value => @room.id %> %>
    <%# <br> %>
    <%# <%= f.submit "投稿する" %> %>
  <%# <% end %> %>
>>>>>>> 82529832332c3e598e92a56a19053079affb55ea

app/views/coaches/top.html.erb
<main id="top_coach">
  <div class="bd-example">
    <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
        <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img src="/default.jpg" class="d-block w-100" alt="...">
          <div class="carousel-caption d-none d-md-block">
            <h5>First slide label</h5>
            <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
          </div>
        </div>
        <div class="carousel-item">
          <img src="/default.jpg" class="d-block w-100" alt="...">
          <div class="carousel-caption d-none d-md-block">
            <h5>Second slide label</h5>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
          </div>
        </div>
        <div class="carousel-item">
          <img src="/default.jpg" class="d-block w-100" alt="...">
          <div class="carousel-caption d-none d-md-block">
            <h5>Third slide label</h5>
            <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>
          </div>
        </div>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </div>
  <div class="bg-lightgray text-center">
    <div class="overflow-hidden">
      <div class="col-sm-2 float-left">
        <img src="/default.jpg" alt="" class="user-icon">
        <p>重神 咲也 (22)</p>
      </div>
      <div class="col-sm-10 overflow-hidden float-left">
        <div class="col-4 float-left">
          <i><img src="/icons/c-mail.png" alt=""></i>
          <p>今週の面談残り</p>
          <h5>3回</h5>
        </div>
        <div class="col-4 float-left">
          <i><img src="/icons/c-mail.png" alt=""></i>
          <p>今月の面談残り</p>
          <h5>33回</h5>
        </div>
        <div class="col-4 float-left">
          <i><img src="/icons/c-mail.png" alt=""></i>
          <p>マイページ閲覧回数</p>
          <h5>321回</h5>
        </div>
        <div class="col-4 float-left">
          <i><img src="/icons/c-mail.png" alt=""></i>
          <p>今週の面談済み</p>
          <h5>5回</h5>
        </div>
        <div class="col-4 float-left">
          <i><img src="/icons/c-mail.png" alt=""></i>
          <p>今月の面談済み</p>
          <h5>12回</h5>
        </div>
        <div class="col-4 float-left">
          <i><img src="/icons/c-mail.png" alt=""></i>
          <p>累計マイページ閲覧回数</p>
          <h5>32,145回</h5>
        </div>
      </div>
    </div>
  </div>
</main>

<%# <script>
  $('.carousel').carousel({
  interval: 5000
})
</script> %>