config/routes.rb
Rails.application.routes.draw do

  root "root#top"
  get "/contact" => "root#contact"

  get 'tests/test'
  get 'tests/mypage'
  get 'tests/favoriteCoach'
  get 'tests/loginPage'
  get 'tests/questionsPage'
  get 'tests/reservationManagementPage'
  get 'tests/contactUsPage'
  get 'tests/topDemoPage'
  get 'tests/chatroom'


  get "users/:user_id/history" => "users#coaching_history", as: :history_user
  get "users/:user_id/reserve_coaching" => "users#reserve_coaching", as: :reserve_user
  get "users/:user_id/settings" => "users#settings", as: :settings_user

  post "users" => "users#create", as: :users
  get "users/new" => "users#new", as: :new_user
  get "users/:user_id/edit" => "users#edit", as: :edit_user
  get "users/:user_id" => "users#show", as: :user_show
  patch "users/:user_id" => "users#update", as: :user_update
  delete "users/:user_id" => "users#destroy", as: :user_destory
  get "detail/users/:user_id" => "users#detail", as: :user_detail
  patch "detail/users/:user_id" => "users#detail_update", as: :user_detail_update
  get "favorite_coach/:user_id" => "users#favorite_coach", as: :favorite_coach

  post "coaches" => "coaches#create", as: :coaches
  get "coaches/new" => "coaches#new", as: :new_coach
  get "coaches/:coach_id/edit" => "coaches#edit", as: :edit_coach
  get "coaches/:coach_id" => "coaches#show", as: :coach_show
  patch "coaches/:coach_id" => "coaches#update", as: :coach_update
  delete "coaches/:coach_id" => "coaches#destroy", as: :coach_destroy
  get "detail/coaches/:coach_id" => "coaches#detail", as: :coach_detail
  patch "detail/coaches/:coach_id" => "coaches#detail_update", as: :coach_detail_update
  get "message_show/coaches/:coach_id" => "coaches#message_show", as: :coach_message_show
  resources :coaches do
    post 'favorites' => 'favorites#create'
    delete 'c_favorites' => 'favorites#destroy'
  end

  get "coaches/:coach_id/review" => "coaches#review", as: :review_coach
  get "coaches/:coach_id/reservation" => "coaches#reservation", as: :reservation_coach
  get "coaches/:coach_id/top" => "coaches#top", as: :top_coach



  get "account_activations/:user_id/user_edit" => "account_activations#edit", as: :user_edit_account_activation
  get "account_activations/:coach_id/coach_edit" => "account_activations#coach_edit", as: :coach_edit_account_activation

  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :events

  get "messages/user_id" => "messages#user_index", as: :user_msg_index
  get "messages/coach_id" => "messages#coach_index", as: :coach_msg_index
  resources :messages, :only => [:create]

  resources :rooms, :only => [:create, :show]

  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"

  get "coach_login" => "coach_sessions#new"
  post "coach_login" => "coach_sessions#create"
  delete "coach_logout" => "coach_sessions#destroy"

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/views/layouts/_footer.html.erb
<footer class="mt-5 pt-5">
  <main class="bg-primary p-6">
    <div class="container text-center">
      <div class="footer-border mt-2 mb-4"></div>
      <div class="row text-white mb-9">
        <a href="#" class="text-white col-1">TOP</a>
        <a href="#" class="text-white col-2">利用規約</a>
        <a href="#" class="text-white col-3 p-0">プライバシーポリシー</a>
        <a href="#" class="text-white col-4">特定商取引法に基づく表記</a>
        <a href="#" class="text-white col-2">会社情報</a>
      </div>
      <h5 class="text-white text-light font-weight-light">2018@Cultiate.inc</h5>
    </div>
  </main>
</footer>

app/views/layouts/_header.html.erb
<header style="margin-bottom:80px;">
  <nav class="navbar nav-tabs navbar-expand-md navbar-dark fixed-top text-center bg-primary">
    <%= link_to "PAISEN", root_path, class:"navbar-brand bg-primary px-4" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto" style="">


      <li class="nav-item col-6">
        <form class="form-inline mt-2 mt-md-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </li>
      <li class="nav-item col-1 ml-4 mt-2">
        <img src="/icons/bell.png" alt="">
      </li>
      <li class="nav-item col-1 mt-2">
        <img src="/icons/mail.png" alt="">
      </li>
      <li class="nav-item col-2 dropdown">
         <a class="nav-link dropdown-toggle text-primary" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
          <img src="/icons/setting.png" alt="">
        </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">コーチング予約管理</a>
            <a class="dropdown-item" href="#">コーチング履歴</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">設定</a>
            <a class="dropdown-item" href="#">ログアウト</a>
          </div>
        </li>
      </ul>
    </div>
  </nav>
</header>

<div class="for_develop" style="border-bottom:3px double gray;">
  <ul class="row">
          <% unless logged_in? || coach_logged_in? %>
          <li class="nav-item">
            <%= link_to "登録（学生）", new_user_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "登録（コーチ）", new_coach_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "ログイン（学生）", login_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "ログイン（コーチ）", coach_login_path, class:"nav-link" %>
          </li>
        <% end %>

        <% if logged_in? %>
          <li class="nav-item">
            <%= link_to "マイページ", user_show_path(user_id: current_user.id), class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "お気に入りコーチ", favorite_coach_path(user_id: current_user.id) %>
          </li>
          <li class="nav-item">
            <%= link_to "メッセージ一覧", user_msg_index_path(id: current_user.id) %>
          </li>
          <li class="nav-item">
            <%= link_to "ログアウト", logout_path, method: "DELETE", class:"nav-link" %>
          </li>
        <% end %>

        <% if coach_logged_in? %>
          <li class="nav-item">
            <%= link_to "cマイページ", coach_show_path(coach_id: current_coach), class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "cログアウト", coach_logout_path, method: "DELETE", class:"nav-link" %>
          </li>
        <% end %>
  </ul>

        <%# <a href="/tests/test">テスト</a>
        <a href="/tests/loginPage">ログイン</a>
        <a href="/tests/reservationManagementPage">予約管理</a>
        <a href="/tests/contactUsPage">問い合わせ</a>
        <a href="/tests/topDemoPage">トップ</a> %>

        <a href="/tests/chatroom">チャット</a>
        <a href="/users/1/reserve_coaching">コーチング予約</a>
        <a href="/users/1/history">コーチング履歴</a>
        <a href="/tests/questionsPage">Q&A</a>
        <a href="/contact">お問い合わせ</a>
        <a href="/coaches/1/review">レビュー</a>
        <a href="/coaches/1/reservation">予約状況</a>
        <a href="/coaches/1/top">コーチトップ</a>

</div>

app/views/layouts/_html_default.html.erb
  <!-- Required Meta Tags Always Come First -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- show new version -->
  <meta http-equiv="X-UA-Compatible" content="ie=edge">

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>

<%= stylesheet_link_tag    'application', media: 'all' %>
<%= javascript_include_tag 'application' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_user_menu.html.erb
        <a href="/tests/test">テスト</a>
        <a href="/tests/mypage">マイページ</a>
        <a href="/tests/favoriteCoach">お気に入りコーチ</a>
        <a href="/tests/loginPage">ログイン</a>
        <a href="/tests/questionsPage">Q&A</a>
        <a href="/tests/reservationManagementPage">予約管理</a>
        <a href="/tests/contactUsPage">問い合わせ</a>
        <a href="/tests/topDemoPage">トップ</a>
        <a href="/tests/chatroom">チャット</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render "layouts/html_default" %>
    <%= render "layouts/rails_default" %>
    <%= render "layouts/shim" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <% flash.each do |msg_type, msg| %>
      <div class="alert alert-<%= msg_type %>">
        <%= msg %>
      </div>
    <% end %>
    <%= yield %>
      <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
      <%= session.to_hash %>
  </body>
</html>